2018-10-23 21:39:11 [scrapy] DEBUG: Crawled (200) <GET https://www.tokopedia.com/robots.txt> (referer: None)
2018-10-23 21:42:11 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads> (failed 1 times): User timeout caused connection failure: Getting https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads took longer than 180.0 seconds..
2018-10-23 21:45:11 [scrapy] DEBUG: Retrying <GET https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads> (failed 2 times): User timeout caused connection failure: Getting https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads took longer than 180.0 seconds..
2018-10-23 22:02:31 [scrapy] DEBUG: Gave up retrying <GET https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads> (failed 3 times): User timeout caused connection failure: Getting https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads took longer than 180.0 seconds..
2018-10-23 22:02:31 [scrapy] ERROR: Error downloading <GET https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads>
Traceback (most recent call last):
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/anaconda2/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/anaconda2/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/anaconda2/lib/python2.7/site-packages/scrapy/core/downloader/handlers/http11.py", line 351, in _cb_timeout
    raise TimeoutError("Getting %s took longer than %s seconds." % (url, timeout))
TimeoutError: User timeout caused connection failure: Getting https://www.tokopedia.com/chocoapple/new-iphone-xs-max-256gb-gold-garansi-apple-1-tahun?src=topads took longer than 180.0 seconds..
2018-10-23 22:02:31 [scrapy] INFO: Closing spider (finished)
2018-10-23 22:02:31 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 3,
 'downloader/exception_type_count/twisted.internet.error.TimeoutError': 3,
 'downloader/request_bytes': 1090,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 539,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 23, 15, 2, 31, 927200),
 'log_count/DEBUG': 21,
 'log_count/ERROR': 1,
 'log_count/INFO': 42,
 'memusage/max': 55222272,
 'memusage/startup': 55222272,
 'response_received_count': 1,
 'retry/count': 2,
 'retry/max_reached': 1,
 'retry/reason_count/twisted.internet.error.TimeoutError': 2,
 'scheduler/dequeued': 3,
 'scheduler/dequeued/memory': 3,
 'scheduler/enqueued': 3,
 'scheduler/enqueued/memory': 3,
 'start_time': datetime.datetime(2018, 10, 23, 14, 39, 10, 743545)}
2018-10-23 22:02:31 [scrapy] INFO: Spider closed (finished)
